service: reto-indra-jm

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:ListTables
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/Appointments
  environment:
    DYNAMODB_APPOINTMENTS: Appointments

functions: ${file(./config/functions.yml)}

resources:
  Resources: ${file(./config/resources.yml)}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  patterns:
    - 'dist/**'            # Incluye todo lo de la carpeta dist
    - 'package.json'       # Incluye el archivo package.json
    - '!node_modules/**'   # Excluye node_modules
    - '!test/**'           # Excluye archivos de prueba
    - '!docs/**'           # Excluye archivos de documentación
