service: reto-indra-jm

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:ListTables
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/Appointments
        - arn:aws:dynamodb:${self:provider.region}:*:table/Appointments/index/insuredIdIndex
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
        - sns:Unsubscribe
        - sns:GetTopicAttributes
        - sns:SetTopicAttributes
        - sns:ListSubscriptionsByTopic
      Resource:
        - arn:aws:sns:${self:provider.region}:*:appointment-created-topic
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:SetQueueAttributes
        - sqs:ListQueues
      Resource:
        - arn:aws:sqs:${self:provider.region}:*:appointment-created-queue-pe
        - arn:aws:sqs:${self:provider.region}:*:appointment-created-queue-cl
        - arn:aws:sqs:${self:provider.region}:*:appointment-created-queue-completed
    - Effect: Allow
      Action:
        - rds:DescribeDBInstances
        - rds:Connect
      Resource:
        - arn:aws:rds:${self:provider.region}:*:db:mysql-pe
        - arn:aws:rds:${self:provider.region}:*:db:mysql-cl
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: arn:aws:events:${self:provider.region}:*:event-bus/appointment-confirm-bus
        
  environment:
    DYNAMODB_APPOINTMENTS: Appointments
    SNS_APPOINTMENT_CREATED_TOPIC_ARN: arn:aws:sns:${self:provider.region}:${aws:accountId}:appointment-created-topic
    EVENT_BUS_NAME: "appointment-confirm-bus"
    EVENT_SOURCE: "com.reto.appointment"
    EVENT_DETAIL_TYPE: "AppointmentCreated"
  
functions: ${file(./config/functions.yml)}

resources:
  Resources: ${file(./config/resources.yml)}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  # - serverless-auto-swagger

package:
  patterns:
    - 'dist/**'
    - 'docs/**'            
    - 'package.json'       
    - '!node_modules/**'   
    - '!test/**'           

# custom:
#   autoswagger:
#     apiType: 'http'
#     basePath: '/'
#     generateSwaggerOnDeploy: true
#     swaggerPath: 'swagger'
#     schemes: ['http', 'https']
#     excludeStages: ['production'] # Opcional
#     title: 'API de Citas Médicas'  # Título de tu API
#     # version: '1.0.0'  # Esto va dentro de info (ver abajo)
#     # info:
#     #   version: '1.0.0'
#     #   description: 'Documentación automática para el sistema de citas médicas'
#     host: 'localhost:3000'  # Solo para desarrollo local