// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API de agendamiento de cita médica para asegurados",
    "version": "1"
  },
  "paths": {
    "/appointment": {
      "post": {
        "summary": "Create new medical appointment",
        "description": "Endpoint to schedule a new medical appointment for an insured patient",
        "tags": [
          "Appointments"
        ],
        "operationId": "createAppointment",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AppointmentRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Appointment created successfully",
            "schema": {
              "$ref": "#/definitions/AppointmentResponse"
            }
          },
          "400": {
            "description": "Invalid input data"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/appointments/{insuredId}": {
      "get": {
        "summary": "Get appointments by insured ID",
        "description": "Retrieve all appointments for a specific insured person",
        "tags": [
          "Appointments"
        ],
        "operationId": "getAppointmentsByInsuredId",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "insuredId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "List of appointments",
            "schema": {
              "$ref": "#/definitions/AppointmentListResponse"
            }
          },
          "404": {
            "description": "No appointments found for this insured ID"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "AppointmentRequest": {
      "properties": {
        "insuredId": {
          "title": "AppointmentRequest.insuredId",
          "type": "string"
        },
        "scheduleId": {
          "title": "AppointmentRequest.scheduleId",
          "type": "number"
        },
        "countryISO": {
          "enum": [
            "PE",
            "CL"
          ],
          "title": "AppointmentRequest.countryISO",
          "type": "string"
        }
      },
      "required": [
        "insuredId",
        "scheduleId",
        "countryISO"
      ],
      "additionalProperties": false,
      "title": "AppointmentRequest",
      "type": "object"
    },
    "AppointmentResponse": {
      "properties": {
        "message": {
          "title": "AppointmentResponse.message",
          "type": "string"
        },
        "appointments": {
          "items": {
            "properties": {
              "id": {
                "title": "AppointmentResponse.appointments.[].id",
                "type": "string"
              },
              "insuredId": {
                "title": "AppointmentResponse.appointments.[].insuredId",
                "type": "string"
              },
              "scheduleId": {
                "title": "AppointmentResponse.appointments.[].scheduleId",
                "type": "number"
              },
              "countryISO": {
                "title": "AppointmentResponse.appointments.[].countryISO",
                "type": "string"
              },
              "status": {
                "enum": [
                  "PENDING",
                  "COMPLETED"
                ],
                "title": "AppointmentResponse.appointments.[].status",
                "type": "string"
              },
              "createdAt": {
                "title": "AppointmentResponse.appointments.[].createdAt",
                "type": "string"
              },
              "updatedAt": {
                "title": "AppointmentResponse.appointments.[].updatedAt",
                "type": "string"
              }
            },
            "required": [
              "id",
              "insuredId",
              "scheduleId",
              "countryISO",
              "status",
              "createdAt",
              "updatedAt"
            ],
            "additionalProperties": false,
            "title": "AppointmentResponse.appointments.[]",
            "type": "object"
          },
          "title": "AppointmentResponse.appointments",
          "type": "array"
        }
      },
      "required": [
        "message",
        "appointments"
      ],
      "additionalProperties": false,
      "title": "AppointmentResponse",
      "type": "object"
    },
    "AppointmentListResponse": {
      "properties": {
        "message": {
          "title": "AppointmentListResponse.message",
          "type": "string"
        },
        "appointments": {
          "title": "AppointmentListResponse.appointments"
        }
      },
      "required": [
        "message",
        "appointments"
      ],
      "additionalProperties": false,
      "title": "AppointmentListResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "host": "k4nit9jt3h.execute-api.us-east-1.amazonaws.com",
  "schemes": [
    "https"
  ]
};