appointment:
  handler: src/infrastructure/handlers/appointmentHandler.handler
  events:
    - http:
        path: appointment
        method: post
    - http:
        path: appointments/{insuredId}
        method: get
    # - eventBridge:
    #     eventBus: agendamientos-event-bus
    #     pattern:
    #       source:
    #         - "com.reto.appointment"
    #       detail-type:
    #         - "AppointmentCreated"
    #       detail:
    #         status:
    #           - "completed"

appointment_pe:
  handler: src/infrastructure/handlers/appointmentPeHandler.main
  events:
    - sqs:
        arn:
          Fn::GetAtt: [AppointmentQueuePESqs, Arn]
        batchSize: 5

appointment_cl:
  handler: src/infrastructure/handlers/appointmentClHandler.main
  events:
    - sqs:
        arn:
          Fn::GetAtt: [AppointmentQueueCLSqs, Arn]
        batchSize: 5
