appointment:
  handler: src/infrastructure/handlers/appointmentHandler.handler
  events:
    - http:
        path: appointments
        method: post
        summary: "Create new medical appointment"
        description: "Endpoint to schedule a new medical appointment for an insured patient"
        swaggerTags: ["Appointments"]
        bodyType: "AppointmentRequest" # Referencia al tipo en tus archivos .d.ts
        responseData:
          201:
            description: "Appointment created successfully"
            bodyType: "AppointmentResponse"
          400:
            description: "Invalid input data"
          500:
            description: "Internal server error"
        operationId: "createAppointment"
    - http:
        path: appointments/{insuredId}
        method: get
        summary: "Get appointments by insured ID"
        description: "Retrieve all appointments for a specific insured person"
        swaggerTags: ["Appointments"]
        responseData:
          200:
            description: "List of appointments"
            bodyType: "AppointmentListResponse"
          404:
            description: "No appointments found for this insured ID"
          500:
            description: "Internal server error"
        operationId: "getAppointmentsByInsuredId"
    - sqs:
          arn:
            Fn::GetAtt: [AppointmentQueueSqsCompleted, Arn]
          batchSize: 1
        
appointment_pe:
  handler: src/infrastructure/handlers/appointmentPeHandler.main
  events:
    - sqs:
        arn:
          Fn::GetAtt: [AppointmentQueuePESqs, Arn]
        batchSize: 5
  environment:
    DB_HOST_PE: ${env:DB_HOST_PE}
    DB_USERNAME_PE: ${env:DB_USER_PE}
    DB_PASSWORD_PE: ${env:DB_PASSWORD_PE}
    DB_NAME_PE: ${env:DB_NAME_PE}
    DB_PORT_PE: ${env:DB_PORT_PE}

appointment_cl:
  handler: src/infrastructure/handlers/appointmentClHandler.main
  events:
    - sqs:
        arn:
          Fn::GetAtt: [AppointmentQueueCLSqs, Arn]
        batchSize: 5
  environment:
    DB_HOST_CL: ${env:DB_HOST_CL}
    DB_USERNAME_CL: ${env:DB_USER_CL}
    DB_PASSWORD_CL: ${env:DB_PASSWORD_CL}
    DB_NAME_CL: ${env:DB_NAME_CL}
    DB_PORT_CL: ${env:DB_PORT_CL}

