AppointmentsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Appointments
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: insuredId
        AttributeType: S
      
    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: insuredIdIndex
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
        Projection:
          ProjectionType: ALL

AppointmentCreatedTopicSns:
  Type: AWS::SNS::Topic
  Properties:
    TopicName: appointment-created-topic

AppointmentCreatedTopicSubscriptionPE:
  Type: AWS::SNS::Subscription
  Properties:
    TopicArn: !Ref AppointmentCreatedTopicSns
    Protocol: sqs
    Endpoint: !GetAtt AppointmentQueuePESqs.Arn
    FilterPolicy:
      countryISO:
        - 'PE'

AppointmentCreatedTopicSubscriptionCL:
  Type: AWS::SNS::Subscription
  Properties:
    TopicArn: !Ref AppointmentCreatedTopicSns
    Protocol: sqs
    Endpoint: !GetAtt AppointmentQueueCLSqs.Arn
    FilterPolicy:
      countryISO:
        - 'CL'

AppointmentQueuePESqs:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: appointment-created-queue-pe

AppointmentQueueCLSqs:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: appointment-created-queue-cl

AppointmentQueueSqsPolicy:
  Type: AWS::SQS::QueuePolicy
  Properties:
    Queues:
      - !Ref AppointmentQueuePESqs
      - !Ref AppointmentQueueCLSqs
    PolicyDocument:
      Statement:
        - Effect: Allow
          Principal: '*'
          Action: SQS:SendMessage
          Resource: !GetAtt AppointmentQueuePESqs.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref AppointmentCreatedTopicSns
        - Effect: Allow
          Principal: '*'
          Action: SQS:SendMessage
          Resource: !GetAtt AppointmentQueueCLSqs.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref AppointmentCreatedTopicSns
    