AppointmentsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Appointments
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: insuredId
        AttributeType: S
      
    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: insuredIdIndex
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      